### PR TITLE
#162685616 Setup an empty react project

### PR DESCRIPTION
**Pull request by Opio-Emmanuel-Omona**
#### What does this PR do?
This PR sets up an empty react project.

#### Description of Task to be completed?
* Setup webpack
* Setup Babel

#### How should this be manually tested?
run the following commands
* git clone https://github.com/andela/Ah-frontend-guardians.git
* git checkout ch-empty-react-project-162685616
* npm install (to install all the dependencies in the package.json)
* npm start

Visit http://localhost:8080/
> The port:8080 may differ

you should see this
image

#### What are the relevant pivotal tracker stories?
https://www.pivotaltracker.com/story/show/162685616

#### References:
I used this to setup the react project
https://www.robinwieruch.de/minimal-react-webpack-babel-setup/

### CODE REVIEW

**Review by myrdstom — APPROVED** [review]
LGTM

**Comment by fahadmak** [comment]
@Opio-Emmanuel-Omona, you don't have App.js set up, please give me more clarity on why it isn't available

**Review by tomuhenry — APPROVED** [review]
LGTM

**Review by fahadmak — CHANGES_REQUESTED** [review]
You have not set up App.js which is the main parent component in the Application tree, please include this file in your PR.

**Review by fahadmak — APPROVED** [review]

**Comment by kisakyegordon** [comment]
@Opio-Emmanuel-Omona 
- @fahadmak raises a good point - consider adding the  `App.js file`

**Pull request merged**
