### PR TITLE
#162685628 User should be able to create Article

### PR DESCRIPTION
**Pull request by moseskamira**
#### What does this PR do?
The PR enables users to;

- Create articles

- Update article

- Delete article their own articles

- Fetch all available articles

- Fetch single article

#### Description of Task to be completed?
Users shall be able to delete and or update their own articles.
Users can also fetch articles that are either authored by themselves or by other authors.
### Relevant Pivotal Tracker story
[#162685628](https://www.pivotaltracker.com/story/show/162685628)

screen shot 2019-02-27 at 5 36 27 pm

### CODE REVIEW

**Review by BarnaTB — CHANGES_REQUESTED** [review]
Please change your PR description to follow the engineering playbook best practices on PRs. Thanks.

Please find the engineering playbook here: https://github.com/andela/engineering-playbook/tree/e654a2dd79972dfe51a1b54d6c7ebc04d2c5e012#pull-requests

**Review by BarnaTB — CHANGES_REQUESTED** [review]
Please fix your circle-CI build. It is currently failing.

**Comment by kisakyegordon** [comment]
@moseskamira why  did you request `Ebun Omoni` for a review - please fix that

**Comment by moseskamira** [comment]
> Please change your PR description to follow the engineering playbook best practices on PRs. Thanks.
> 
> Please find the engineering playbook here: https://github.com/andela/engineering-playbook/tree/e654a2dd79972dfe51a1b54d6c7ebc04d2c5e012#pull-requests

Implemented requested changes

**Comment by kisakyegordon** [comment]
@moseskamira `codeclimate` checks are failing

**Comment by kisakyegordon** [comment]
@moseskamira Please make the  Pivotal  Tracker `iD` an actual link to the story

**Comment by kisakyegordon** [comment]
@moseskamira Kindly add some images of  the parts you worked on

**Comment by moseskamira** [comment]
> Please fix your circle-CI build. It is currently failing.

Fixed

**Comment by moseskamira** [comment]
> @moseskamira Kindly add some images of the parts you worked on

Worked on

**Pull request merged**
