### PR TITLE
#163935489 Update the README file

### PR DESCRIPTION
**Pull request by tomuhenry**
**What does this PR do?**
This PR Updates the README.md file with badges and how the app can be tested locally

**Description of Task to be completed?**
- Add CircleCI badge
- Add TravisCI badge
- Add Hound badge
- Updated CircleCI.yml file to get test coverage report from Codeclimate
- Add the Codeclimate Test Coverage badge

**How should this be tested?**
- Go to this repository [Here](https://github.com/andela/Ah-frontend-guardians/tree/develop) and go to the develop branch
- To see the badges if not merged yet,  go to this [Link](https://github.com/andela/Ah-frontend-guardians/tree/ch-update-README-163935489)
- `Test Coverage` badge shows **unknown** on the `ch-update-README-163935489` branch because it points to the develop branch

**Relevant pivotal tracker stories**
[#163935489](https://www.pivotaltracker.com/story/show/163935489)

screen shot 2019-02-13 at 5 11 02 pm

### CODE REVIEW

**Comment by Opio-Emmanuel-Omona** [comment]
@tomuhenry Great work
image
Though I think this section of the PR description is inaccurate, after cloning the repo and I run `npm start`, I'm running the app on the default branch and not the branch for this chore.

I think a better way to test it would be inserting a link to your branch and showing us a screenshot of the badges in the ReadMe

**Comment by tomuhenry** [comment]
https://github.com/andela/Ah-frontend-guardians/pull/12#issuecomment-463175813 
@Opio-Emmanuel-Omona [PT Story](https://www.pivotaltracker.com/story/show/163935489) says that I should describe how the app should be set up locally.
This PR doesn't need testing so I might need to edit that.

**Comment by Opio-Emmanuel-Omona** [comment]
https://github.com/andela/Ah-frontend-guardians/pull/12#issuecomment-463212458
@tomuhenry  Okay cool

**Review by Opio-Emmanuel-Omona — APPROVED** [review]

**Review by BarnaTB — APPROVED** [review]
LGTM!

**Pull request merged**
