### PR TITLE
#162685632 Users can like and or dislike an article

### PR DESCRIPTION
**Pull request by Opio-Emmanuel-Omona**
#### What does this PR do?
This PR enables only authenticate users to like and unlike an article whether or not it was authored by them.

#### Description of Task to be completed?
* Like and unlike article functionality
* Dislike and Undislike Article functipnality
* UI for like and dislike

#### How should this be manually tested?
```Use the appropriate screenshots to test the expected results```
* Visit the URL below:
https://ah-frontend-guardians-pr-20.herokuapp.com/

* Click on an article
* Then you can click on the like and or dislike buttons

#### What are the relevant pivotal tracker stories?
[#162685632](https://www.pivotaltracker.com/story/show/162685632)

#### Screenshots 
image

image

### CODE REVIEW

**Comment by myrdstom** [comment]
@Opio-Emmanuel-Omona Your like and unlike buttons are a bit off as compared to the mockups. You could try to fix them or we can discuss the display as a team

**Review by myrdstom — COMMENTED** [review]
@Opio-Emmanuel-Omona Your like and unlike buttons are a bit off as compared to the mockups. You could try to fix them or we can discuss the display as a team

**Comment by Opio-Emmanuel-Omona** [comment]
https://github.com/andela/Ah-frontend-guardians/pull/20#pullrequestreview-210006418

@myrdstom , I have fixed the issue with the alignment of the like and dislike icons.

**Review by myrdstom — APPROVED** [review]
LGTM

**Review by moseskamira — APPROVED** [review]
LGTM

**Pull request merged**
