### PR TITLE
#162685646 Users can view their reading stats

### PR DESCRIPTION
**Pull request by Opio-Emmanuel-Omona**
#### What does this PR do?
This PR enables authenticated users to view their reading stats

#### Description of Task to be completed?
* design the UI for reading stats
* add reading stats tab in the profile page
* do a get functionality for reading stats
* write necessary test

#### How should this be manually tested?
* Visit the URL below:
https://ah-frontend-guardians-pr-30.herokuapp.com/

* `Login` > `Profile`  and then select the `statistics` tab

* Note to read a story, all you have to do is a click on an article from the landing page while logged in.
* Then come back to the profile page and assert that it added the new article among your reading stats.
* No stats will be added if you try to read your own article.

* You can also click `view article` to read the article again.

#### What are the relevant pivotal tracker stories?
[ #162685646](https://www.pivotaltracker.com/story/show/162685646)

#### Screenshots (if appropriate)
image

### CODE REVIEW

**Review by myrdstom — COMMENTED** [review]
@Opio-Emmanuel-Omona there is a glitch in your feature. It seems when I read a new article, it does not display under the "recently read articles" tab. It did not show me the articles I had recently read when I tested it

**Comment by Opio-Emmanuel-Omona** [comment]
@myrdstom I think it's because you had previously read them, So it doesn't update an article that you have already read. And also when you read your own article, that statistic isn't tracked.

**Review by myrdstom — APPROVED** [review]
LGTM

**Review by moseskamira — APPROVED** [review]
LGTM

**Pull request merged**
