### PR TITLE
#162685628 Users can Edit and Delete their articles

### PR DESCRIPTION
**Pull request by Opio-Emmanuel-Omona**
#### What does this PR do?
This PR enables users to edit and delete articles that they authored.

#### Description of Task to be completed?
* Implement update and delete functionality from the profile page
* design the User interface for performing the functionality

#### How should this be manually tested?
Use the appropriate screenshots provided to view the expected results
* Visit the url below:
https://ah-frontend-guardians-pr-18.herokuapp.com/

* signup and login
* click on the avatar profile avatar to view your profile page.
* If you don't have any articles you have to post some using postman.
```POST https://ah-backend-guardians-staging.herokuapp.com/api/articles/```

```
Note: Remember to use the surrent token after a login, get from the browser local storage
{
	"title": "",
	"description": "",
	"body": ""
}
```
* After posting, you can refresh the profile page and you should see articles you posted
* Hit the delete button
* Then confirm the action
* Hit the edit button
* Edit the article and save the changes

#### What are the relevant pivotal tracker stories?
[#162685628](https://www.pivotaltracker.com/story/show/162685628)

#### Screenshots
image

image

image

image

image

### CODE REVIEW

**Comment by BarnaTB** [comment]
@Opio-Emmanuel-Omona could you please fix the failing circle-ci build?

**Comment by BarnaTB** [comment]
Great work @Opio-Emmanuel-Omona but I think you should change the display of the avatar because when I sign in and I don't have any articles, it shows the avatar and tells me I don't have any articles yet but when I have articles it displays the sign in and register links in the navBar, in place of the avatar. It'd be nice if you kindly look into this.

**Review by BarnaTB — CHANGES_REQUESTED** [review]
Great work @Opio-Emmanuel-Omona. You have pulled off the look that is in the mockups and this is great stuff. You might want to kindly give the edit article text boxes some `margin-top` so that they're not attached to the navBar.

**Review by moseskamira — APPROVED** [review]
LGTM

**Review by BarnaTB — APPROVED** [review]
LGTM great work!

**Review by kisakyegordon — APPROVED** [review]

**Pull request merged**
